import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "moment/locale/id";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        <main className="container min-h-screen">
          {children}
        </main>
        <footer className="p-[40px] bg-zinc-100 mt-[10px]">
          Made By Akmal
        </footer>
      </body>
    </html>
  );
}
